### ISSUE TITLE
Review and merge all upstream's pull requests

### ISSUE THREAD

**Issue by omissis** [omissis/go-jsonschema#53]
**List of PRs**

- [x] atombender/go-jsonschema#47 
- [x] atombender/go-jsonschema#45
- [x] atombender/go-jsonschema#43
- [x] atombender/go-jsonschema#40
- [x] atombender/go-jsonschema#39
- [x] atombender/go-jsonschema#23
- [x] atombender/go-jsonschema#21

**Notes**

This is a port of my former fork's issue https://github.com/omissis/go-jsonschema-fork/issues/3

**Comment by omissis** [comment]
I reviewed all the open PRs and merged most of them in main. Since this work was done at the time when this repository was a fork of the original one (atombender/go-jsonschema) which has now been transferred to me, all the changes happened in #52.
The only PRs I haven't merged are the ones related to validation, as I want to take the time to explore the integration of go-playground's validation library to address as many cases as possible.
